// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef STORE_ODB_HXX
#define STORE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "store.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Album
  //
  template <>
  struct class_traits< ::imgr::model::Album >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::imgr::model::Album >
  {
    public:
    typedef ::imgr::model::Album object_type;
    typedef ::std::shared_ptr< ::imgr::model::Album > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::imgr::model::Album::id_type id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // Photo
  //
  template <>
  struct class_traits< ::imgr::model::Photo >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::imgr::model::Photo >
  {
    public:
    typedef ::imgr::model::Photo object_type;
    typedef ::std::shared_ptr< ::imgr::model::Photo > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::imgr::model::Photo::id_type id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // PhotoThumbnail
  //
  template <>
  struct class_traits< ::imgr::model::PhotoThumbnail >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::imgr::model::PhotoThumbnail >
  {
    public:
    typedef ::imgr::model::PhotoThumbnail object_type;
    typedef ::std::shared_ptr< ::imgr::model::PhotoThumbnail > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::imgr::model::PhotoThumbnail::id_type id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // Album
  //
  template <typename A>
  struct pointer_query_columns< ::imgr::model::Album, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Album::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // absolute_path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    absolute_path_type_;

    static const absolute_path_type_ absolute_path;

    // name
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    name_type_;

    static const name_type_ name;

    // parent_album
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Album::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    parent_album_type_;

    static const parent_album_type_ parent_album;
  };

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::id_type_
  pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::absolute_path_type_
  pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::
  absolute_path (A::table_name, "\"absolute_path\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::name_type_
  pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::parent_album_type_
  pointer_query_columns< ::imgr::model::Album, id_sqlite, A >::
  parent_album (A::table_name, "\"parent_album\"", 0);

  template <>
  class access::object_traits_impl< ::imgr::model::Album, id_sqlite >:
    public access::object_traits< ::imgr::model::Album >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // m_id
      //
      long long m_id_value;
      bool m_id_null;

      // m_absolute_path
      //
      details::buffer m_absolute_path_value;
      std::size_t m_absolute_path_size;
      bool m_absolute_path_null;

      // m_name
      //
      details::buffer m_name_value;
      std::size_t m_name_size;
      bool m_name_null;

      // m_parent_album
      //
      long long m_parent_album_value;
      bool m_parent_album_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct parent_album_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::imgr::model::Album, id_common >:
    public access::object_traits_impl< ::imgr::model::Album, id_sqlite >
  {
  };

  // Photo
  //
  template <typename A>
  struct pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Photo::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // filename
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    filename_type_;

    static const filename_type_ filename;

    // width
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    width_type_;

    static const width_type_ width;

    // height
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    height_type_;

    static const height_type_ height;

    // album
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Album::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    album_type_;

    static const album_type_ album;
  };

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::id_type_
  pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::filename_type_
  pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::
  filename (A::table_name, "\"filename\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::width_type_
  pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::
  width (A::table_name, "\"width\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::height_type_
  pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::
  height (A::table_name, "\"height\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::album_type_
  pointer_query_columns< ::imgr::model::Photo, id_sqlite, A >::
  album (A::table_name, "\"album\"", 0);

  template <>
  class access::object_traits_impl< ::imgr::model::Photo, id_sqlite >:
    public access::object_traits< ::imgr::model::Photo >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // m_id
      //
      long long m_id_value;
      bool m_id_null;

      // m_filename
      //
      details::buffer m_filename_value;
      std::size_t m_filename_size;
      bool m_filename_null;

      // m_width
      //
      long long m_width_value;
      bool m_width_null;

      // m_height
      //
      long long m_height_value;
      bool m_height_null;

      // m_album
      //
      long long m_album_value;
      bool m_album_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct album_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::imgr::model::Photo, id_common >:
    public access::object_traits_impl< ::imgr::model::Photo, id_sqlite >
  {
  };

  // PhotoThumbnail
  //
  template <typename A>
  struct pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::PhotoThumbnail::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // width
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    width_type_;

    static const width_type_ width;

    // height
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    height_type_;

    static const height_type_ height;

    // channels
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint8_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    channels_type_;

    static const channels_type_ channels;

    // thumbnail
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::RawData,
        sqlite::id_blob >::query_type,
      sqlite::id_blob >
    thumbnail_type_;

    static const thumbnail_type_ thumbnail;

    // photo
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Photo::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    photo_type_;

    static const photo_type_ photo;
  };

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::id_type_
  pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::width_type_
  pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  width (A::table_name, "\"width\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::height_type_
  pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  height (A::table_name, "\"height\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::channels_type_
  pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  channels (A::table_name, "\"channels\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::thumbnail_type_
  pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  thumbnail (A::table_name, "\"thumbnail\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::photo_type_
  pointer_query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  photo (A::table_name, "\"photo\"", 0);

  template <>
  class access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >:
    public access::object_traits< ::imgr::model::PhotoThumbnail >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // m_id
      //
      long long m_id_value;
      bool m_id_null;

      // m_width
      //
      long long m_width_value;
      bool m_width_null;

      // m_height
      //
      long long m_height_value;
      bool m_height_null;

      // m_channels
      //
      long long m_channels_value;
      bool m_channels_null;

      // m_thumbnail
      //
      details::buffer m_thumbnail_value;
      std::size_t m_thumbnail_size;
      bool m_thumbnail_null;

      // m_photo
      //
      long long m_photo_value;
      bool m_photo_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct photo_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_common >:
    public access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >
  {
  };

  // Album
  //
  template <>
  struct alias_traits<
    ::imgr::model::Album,
    id_sqlite,
    access::object_traits_impl< ::imgr::model::Album, id_sqlite >::parent_album_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::imgr::model::Album, id_sqlite >
  {
    // parent_album
    //
    typedef
    odb::alias_traits<
      ::imgr::model::Album,
      id_sqlite,
      access::object_traits_impl< ::imgr::model::Album, id_sqlite >::parent_album_tag>
    parent_album_alias_;
  };

  template <typename A>
  struct query_columns< ::imgr::model::Album, id_sqlite, A >:
    query_columns_base< ::imgr::model::Album, id_sqlite >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Album::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // absolute_path
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    absolute_path_type_;

    static const absolute_path_type_ absolute_path;

    // name
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    name_type_;

    static const name_type_ name;

    // parent_album
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Album::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    parent_album_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::imgr::model::Album,
        id_sqlite,
        parent_album_alias_ > >
    parent_album_pointer_type_;

    struct parent_album_type_: parent_album_pointer_type_, parent_album_column_type_
    {
      parent_album_type_ (const char* t, const char* c, const char* conv)
        : parent_album_column_type_ (t, c, conv)
      {
      }
    };

    static const parent_album_type_ parent_album;
  };

  template <typename A>
  const typename query_columns< ::imgr::model::Album, id_sqlite, A >::id_type_
  query_columns< ::imgr::model::Album, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Album, id_sqlite, A >::absolute_path_type_
  query_columns< ::imgr::model::Album, id_sqlite, A >::
  absolute_path (A::table_name, "\"absolute_path\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Album, id_sqlite, A >::name_type_
  query_columns< ::imgr::model::Album, id_sqlite, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Album, id_sqlite, A >::parent_album_type_
  query_columns< ::imgr::model::Album, id_sqlite, A >::
  parent_album (A::table_name, "\"parent_album\"", 0);

  // Photo
  //
  template <>
  struct alias_traits<
    ::imgr::model::Album,
    id_sqlite,
    access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::album_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::imgr::model::Photo, id_sqlite >
  {
    // album
    //
    typedef
    odb::alias_traits<
      ::imgr::model::Album,
      id_sqlite,
      access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::album_tag>
    album_alias_;
  };

  template <typename A>
  struct query_columns< ::imgr::model::Photo, id_sqlite, A >:
    query_columns_base< ::imgr::model::Photo, id_sqlite >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Photo::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // filename
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    filename_type_;

    static const filename_type_ filename;

    // width
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    width_type_;

    static const width_type_ width;

    // height
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    height_type_;

    static const height_type_ height;

    // album
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Album::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    album_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::imgr::model::Album,
        id_sqlite,
        album_alias_ > >
    album_pointer_type_;

    struct album_type_: album_pointer_type_, album_column_type_
    {
      album_type_ (const char* t, const char* c, const char* conv)
        : album_column_type_ (t, c, conv)
      {
      }
    };

    static const album_type_ album;
  };

  template <typename A>
  const typename query_columns< ::imgr::model::Photo, id_sqlite, A >::id_type_
  query_columns< ::imgr::model::Photo, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Photo, id_sqlite, A >::filename_type_
  query_columns< ::imgr::model::Photo, id_sqlite, A >::
  filename (A::table_name, "\"filename\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Photo, id_sqlite, A >::width_type_
  query_columns< ::imgr::model::Photo, id_sqlite, A >::
  width (A::table_name, "\"width\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Photo, id_sqlite, A >::height_type_
  query_columns< ::imgr::model::Photo, id_sqlite, A >::
  height (A::table_name, "\"height\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::Photo, id_sqlite, A >::album_type_
  query_columns< ::imgr::model::Photo, id_sqlite, A >::
  album (A::table_name, "\"album\"", 0);

  // PhotoThumbnail
  //
  template <>
  struct alias_traits<
    ::imgr::model::Photo,
    id_sqlite,
    access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::photo_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::imgr::model::PhotoThumbnail, id_sqlite >
  {
    // photo
    //
    typedef
    odb::alias_traits<
      ::imgr::model::Photo,
      id_sqlite,
      access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::photo_tag>
    photo_alias_;
  };

  template <typename A>
  struct query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >:
    query_columns_base< ::imgr::model::PhotoThumbnail, id_sqlite >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::PhotoThumbnail::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // width
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    width_type_;

    static const width_type_ width;

    // height
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint16_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    height_type_;

    static const height_type_ height;

    // channels
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::uint8_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    channels_type_;

    static const channels_type_ channels;

    // thumbnail
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::RawData,
        sqlite::id_blob >::query_type,
      sqlite::id_blob >
    thumbnail_type_;

    static const thumbnail_type_ thumbnail;

    // photo
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::imgr::model::Photo::id_type,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    photo_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::imgr::model::Photo,
        id_sqlite,
        photo_alias_ > >
    photo_pointer_type_;

    struct photo_type_: photo_pointer_type_, photo_column_type_
    {
      photo_type_ (const char* t, const char* c, const char* conv)
        : photo_column_type_ (t, c, conv)
      {
      }
    };

    static const photo_type_ photo;
  };

  template <typename A>
  const typename query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::id_type_
  query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::width_type_
  query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  width (A::table_name, "\"width\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::height_type_
  query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  height (A::table_name, "\"height\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::channels_type_
  query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  channels (A::table_name, "\"channels\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::thumbnail_type_
  query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  thumbnail (A::table_name, "\"thumbnail\"", 0);

  template <typename A>
  const typename query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::photo_type_
  query_columns< ::imgr::model::PhotoThumbnail, id_sqlite, A >::
  photo (A::table_name, "\"photo\"", 0);
}

#include "store-odb.ixx"

#include <odb/post.hxx>

#endif // STORE_ODB_HXX
