version: "3.1"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password0!
    ports:
      - "5432:5432"

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jorelmb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Password0!
    ports:
      - "8080:80"