/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Photo" CASCADE;

DROP TABLE IF EXISTS "Album" CASCADE;

CREATE TABLE "Album" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "absolute_path" TEXT NOT NULL);

CREATE TABLE "Photo" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "filename" TEXT NOT NULL,
  "width" INTEGER NOT NULL,
  "height" INTEGER NOT NULL,
  "thumbnail" BYTEA NOT NULL,
  "album" BIGINT NOT NULL,
  CONSTRAINT "album_fk"
    FOREIGN KEY ("album")
    REFERENCES "Album" ("id")
    INITIALLY DEFERRED);

