// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "store-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // Album
  //

  const char alias_traits<  ::imgr::model::Album,
    id_sqlite,
    access::object_traits_impl< ::imgr::model::Album, id_sqlite >::parent_album_tag>::
  table_name[] = "\"parent_album\"";

  struct access::object_traits_impl< ::imgr::model::Album, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::id_type
  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::imgr::model::Album::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::id_type
  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::imgr::model::Album::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.m_id_value,
        i.m_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_id
    //
    t[0UL] = false;

    // m_absolute_path
    //
    if (t[1UL])
    {
      i.m_absolute_path_value.capacity (i.m_absolute_path_size);
      grew = true;
    }

    // m_name
    //
    if (t[2UL])
    {
      i.m_name_value.capacity (i.m_name_size);
      grew = true;
    }

    // m_parent_album
    //
    t[3UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // m_id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.m_id_value;
      b[n].is_null = &i.m_id_null;
      n++;
    }

    // m_absolute_path
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_absolute_path_value.data ();
    b[n].size = &i.m_absolute_path_size;
    b[n].capacity = i.m_absolute_path_value.capacity ();
    b[n].is_null = &i.m_absolute_path_null;
    n++;

    // m_name
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_name_value.data ();
    b[n].size = &i.m_name_size;
    b[n].capacity = i.m_name_value.capacity ();
    b[n].is_null = &i.m_name_null;
    n++;

    // m_parent_album
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_parent_album_value;
    b[n].is_null = &i.m_parent_album_null;
    n++;
  }

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // m_id
    //
    if (sk == statement_insert)
    {
      ::imgr::model::Album::id_type const& v =
        o.m_id;

      bool is_null (false);
      sqlite::value_traits<
          ::imgr::model::Album::id_type,
          sqlite::id_integer >::set_image (
        i.m_id_value,
        is_null,
        v);
      i.m_id_null = is_null;
    }

    // m_absolute_path
    //
    {
      ::std::string const& v =
        o.m_absolute_path;

      bool is_null (false);
      std::size_t cap (i.m_absolute_path_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_absolute_path_value,
        i.m_absolute_path_size,
        is_null,
        v);
      i.m_absolute_path_null = is_null;
      grew = grew || (cap != i.m_absolute_path_value.capacity ());
    }

    // m_name
    //
    {
      ::std::string const& v =
        o.m_name;

      bool is_null (false);
      std::size_t cap (i.m_name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_name_value,
        i.m_name_size,
        is_null,
        v);
      i.m_name_null = is_null;
      grew = grew || (cap != i.m_name_value.capacity ());
    }

    // m_parent_album
    //
    {
      ::std::shared_ptr< ::imgr::model::Album > const& v =
        o.m_parent_album;

      typedef object_traits< ::imgr::model::Album > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::imgr::model::Album > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i.m_parent_album_value,
          is_null,
          id);
        i.m_parent_album_null = is_null;
      }
      else
        i.m_parent_album_null = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_id
    //
    {
      ::imgr::model::Album::id_type& v =
        o.m_id;

      sqlite::value_traits<
          ::imgr::model::Album::id_type,
          sqlite::id_integer >::set_value (
        v,
        i.m_id_value,
        i.m_id_null);
    }

    // m_absolute_path
    //
    {
      ::std::string& v =
        o.m_absolute_path;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_absolute_path_value,
        i.m_absolute_path_size,
        i.m_absolute_path_null);
    }

    // m_name
    //
    {
      ::std::string& v =
        o.m_name;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_name_value,
        i.m_name_size,
        i.m_name_null);
    }

    // m_parent_album
    //
    {
      ::std::shared_ptr< ::imgr::model::Album >& v =
        o.m_parent_album;

      typedef object_traits< ::imgr::model::Album > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::imgr::model::Album > > ptr_traits;

      if (i.m_parent_album_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i.m_parent_album_value,
          i.m_parent_album_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::imgr::model::Album::id_type,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Album\" "
  "(\"id\", "
  "\"absolute_path\", "
  "\"name\", "
  "\"parent_album\") "
  "VALUES "
  "(?, ?, ?, ?)";

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::find_statement[] =
  "SELECT "
  "\"Album\".\"id\", "
  "\"Album\".\"absolute_path\", "
  "\"Album\".\"name\", "
  "\"Album\".\"parent_album\" "
  "FROM \"Album\" "
  "WHERE \"Album\".\"id\"=?";

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::update_statement[] =
  "UPDATE \"Album\" "
  "SET "
  "\"absolute_path\"=?, "
  "\"name\"=?, "
  "\"parent_album\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Album\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"Album\".\"id\",\n"
  "\"Album\".\"absolute_path\",\n"
  "\"Album\".\"name\",\n"
  "\"Album\".\"parent_album\"\n"
  "FROM \"Album\"\n"
  "LEFT JOIN \"Album\" AS \"parent_album\" ON \"parent_album\".\"id\"=\"Album\".\"parent_album\"";

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Album\"";

  const char access::object_traits_impl< ::imgr::model::Album, id_sqlite >::table_name[] =
  "\"Album\"";

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.m_id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.m_id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::pointer_type
  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::imgr::model::Album, id_sqlite >::object_type >
  access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::imgr::model::Album, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // Photo
  //

  const char alias_traits<  ::imgr::model::Album,
    id_sqlite,
    access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::album_tag>::
  table_name[] = "\"album\"";

  struct access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::id_type
  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::imgr::model::Photo::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::id_type
  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::imgr::model::Photo::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.m_id_value,
        i.m_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_id
    //
    t[0UL] = false;

    // m_filename
    //
    if (t[1UL])
    {
      i.m_filename_value.capacity (i.m_filename_size);
      grew = true;
    }

    // m_width
    //
    t[2UL] = false;

    // m_height
    //
    t[3UL] = false;

    // m_album
    //
    t[4UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // m_id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.m_id_value;
      b[n].is_null = &i.m_id_null;
      n++;
    }

    // m_filename
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_filename_value.data ();
    b[n].size = &i.m_filename_size;
    b[n].capacity = i.m_filename_value.capacity ();
    b[n].is_null = &i.m_filename_null;
    n++;

    // m_width
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_width_value;
    b[n].is_null = &i.m_width_null;
    n++;

    // m_height
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_height_value;
    b[n].is_null = &i.m_height_null;
    n++;

    // m_album
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_album_value;
    b[n].is_null = &i.m_album_null;
    n++;
  }

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // m_id
    //
    if (sk == statement_insert)
    {
      ::imgr::model::Photo::id_type const& v =
        o.m_id;

      bool is_null (false);
      sqlite::value_traits<
          ::imgr::model::Photo::id_type,
          sqlite::id_integer >::set_image (
        i.m_id_value,
        is_null,
        v);
      i.m_id_null = is_null;
    }

    // m_filename
    //
    {
      ::std::string const& v =
        o.m_filename;

      bool is_null (false);
      std::size_t cap (i.m_filename_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.m_filename_value,
        i.m_filename_size,
        is_null,
        v);
      i.m_filename_null = is_null;
      grew = grew || (cap != i.m_filename_value.capacity ());
    }

    // m_width
    //
    {
      ::uint16_t const& v =
        o.m_width;

      bool is_null (false);
      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_image (
        i.m_width_value,
        is_null,
        v);
      i.m_width_null = is_null;
    }

    // m_height
    //
    {
      ::uint16_t const& v =
        o.m_height;

      bool is_null (false);
      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_image (
        i.m_height_value,
        is_null,
        v);
      i.m_height_null = is_null;
    }

    // m_album
    //
    {
      ::std::shared_ptr< ::imgr::model::Album > const& v =
        o.m_album;

      typedef object_traits< ::imgr::model::Album > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::imgr::model::Album > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i.m_album_value,
          is_null,
          id);
        i.m_album_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_id
    //
    {
      ::imgr::model::Photo::id_type& v =
        o.m_id;

      sqlite::value_traits<
          ::imgr::model::Photo::id_type,
          sqlite::id_integer >::set_value (
        v,
        i.m_id_value,
        i.m_id_null);
    }

    // m_filename
    //
    {
      ::std::string& v =
        o.m_filename;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i.m_filename_value,
        i.m_filename_size,
        i.m_filename_null);
    }

    // m_width
    //
    {
      ::uint16_t& v =
        o.m_width;

      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_width_value,
        i.m_width_null);
    }

    // m_height
    //
    {
      ::uint16_t& v =
        o.m_height;

      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_height_value,
        i.m_height_null);
    }

    // m_album
    //
    {
      ::std::shared_ptr< ::imgr::model::Album >& v =
        o.m_album;

      typedef object_traits< ::imgr::model::Album > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::imgr::model::Album > > ptr_traits;

      if (i.m_album_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i.m_album_value,
          i.m_album_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::imgr::model::Photo::id_type,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Photo\" "
  "(\"id\", "
  "\"filename\", "
  "\"width\", "
  "\"height\", "
  "\"album\") "
  "VALUES "
  "(?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::find_statement[] =
  "SELECT "
  "\"Photo\".\"id\", "
  "\"Photo\".\"filename\", "
  "\"Photo\".\"width\", "
  "\"Photo\".\"height\", "
  "\"Photo\".\"album\" "
  "FROM \"Photo\" "
  "WHERE \"Photo\".\"id\"=?";

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::update_statement[] =
  "UPDATE \"Photo\" "
  "SET "
  "\"filename\"=?, "
  "\"width\"=?, "
  "\"height\"=?, "
  "\"album\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Photo\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"Photo\".\"id\",\n"
  "\"Photo\".\"filename\",\n"
  "\"Photo\".\"width\",\n"
  "\"Photo\".\"height\",\n"
  "\"Photo\".\"album\"\n"
  "FROM \"Photo\"\n"
  "LEFT JOIN \"Album\" AS \"album\" ON \"album\".\"id\"=\"Photo\".\"album\"";

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Photo\"";

  const char access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::table_name[] =
  "\"Photo\"";

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.m_id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.m_id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::pointer_type
  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::object_type >
  access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::imgr::model::Photo, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // PhotoThumbnail
  //

  const char alias_traits<  ::imgr::model::Photo,
    id_sqlite,
    access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::photo_tag>::
  table_name[] = "\"photo\"";

  struct access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::id_type
  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::imgr::model::PhotoThumbnail::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::id_type
  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::imgr::model::PhotoThumbnail::id_type,
          sqlite::id_integer >::set_value (
        id,
        i.m_id_value,
        i.m_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_id
    //
    t[0UL] = false;

    // m_width
    //
    t[1UL] = false;

    // m_height
    //
    t[2UL] = false;

    // m_channels
    //
    t[3UL] = false;

    // m_thumbnail
    //
    if (t[4UL])
    {
      i.m_thumbnail_value.capacity (i.m_thumbnail_size);
      grew = true;
    }

    // m_photo
    //
    t[5UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // m_id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.m_id_value;
      b[n].is_null = &i.m_id_null;
      n++;
    }

    // m_width
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_width_value;
    b[n].is_null = &i.m_width_null;
    n++;

    // m_height
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_height_value;
    b[n].is_null = &i.m_height_null;
    n++;

    // m_channels
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_channels_value;
    b[n].is_null = &i.m_channels_null;
    n++;

    // m_thumbnail
    //
    b[n].type = sqlite::bind::blob;
    b[n].buffer = i.m_thumbnail_value.data ();
    b[n].size = &i.m_thumbnail_size;
    b[n].capacity = i.m_thumbnail_value.capacity ();
    b[n].is_null = &i.m_thumbnail_null;
    n++;

    // m_photo
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_photo_value;
    b[n].is_null = &i.m_photo_null;
    n++;
  }

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // m_id
    //
    if (sk == statement_insert)
    {
      ::imgr::model::PhotoThumbnail::id_type const& v =
        o.m_id;

      bool is_null (false);
      sqlite::value_traits<
          ::imgr::model::PhotoThumbnail::id_type,
          sqlite::id_integer >::set_image (
        i.m_id_value,
        is_null,
        v);
      i.m_id_null = is_null;
    }

    // m_width
    //
    {
      ::uint16_t const& v =
        o.m_width;

      bool is_null (false);
      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_image (
        i.m_width_value,
        is_null,
        v);
      i.m_width_null = is_null;
    }

    // m_height
    //
    {
      ::uint16_t const& v =
        o.m_height;

      bool is_null (false);
      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_image (
        i.m_height_value,
        is_null,
        v);
      i.m_height_null = is_null;
    }

    // m_channels
    //
    {
      ::uint8_t const& v =
        o.m_channels;

      bool is_null (false);
      sqlite::value_traits<
          ::uint8_t,
          sqlite::id_integer >::set_image (
        i.m_channels_value,
        is_null,
        v);
      i.m_channels_null = is_null;
    }

    // m_thumbnail
    //
    {
      ::imgr::model::RawData const& v =
        o.m_thumbnail;

      bool is_null (false);
      std::size_t cap (i.m_thumbnail_value.capacity ());
      sqlite::value_traits<
          ::imgr::model::RawData,
          sqlite::id_blob >::set_image (
        i.m_thumbnail_value,
        i.m_thumbnail_size,
        is_null,
        v);
      i.m_thumbnail_null = is_null;
      grew = grew || (cap != i.m_thumbnail_value.capacity ());
    }

    // m_photo
    //
    {
      ::std::shared_ptr< ::imgr::model::Photo > const& v =
        o.m_photo;

      typedef object_traits< ::imgr::model::Photo > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::imgr::model::Photo > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i.m_photo_value,
          is_null,
          id);
        i.m_photo_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_id
    //
    {
      ::imgr::model::PhotoThumbnail::id_type& v =
        o.m_id;

      sqlite::value_traits<
          ::imgr::model::PhotoThumbnail::id_type,
          sqlite::id_integer >::set_value (
        v,
        i.m_id_value,
        i.m_id_null);
    }

    // m_width
    //
    {
      ::uint16_t& v =
        o.m_width;

      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_width_value,
        i.m_width_null);
    }

    // m_height
    //
    {
      ::uint16_t& v =
        o.m_height;

      sqlite::value_traits<
          ::uint16_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_height_value,
        i.m_height_null);
    }

    // m_channels
    //
    {
      ::uint8_t& v =
        o.m_channels;

      sqlite::value_traits<
          ::uint8_t,
          sqlite::id_integer >::set_value (
        v,
        i.m_channels_value,
        i.m_channels_null);
    }

    // m_thumbnail
    //
    {
      ::imgr::model::RawData& v =
        o.m_thumbnail;

      sqlite::value_traits<
          ::imgr::model::RawData,
          sqlite::id_blob >::set_value (
        v,
        i.m_thumbnail_value,
        i.m_thumbnail_size,
        i.m_thumbnail_null);
    }

    // m_photo
    //
    {
      ::std::shared_ptr< ::imgr::model::Photo >& v =
        o.m_photo;

      typedef object_traits< ::imgr::model::Photo > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::imgr::model::Photo > > ptr_traits;

      if (i.m_photo_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i.m_photo_value,
          i.m_photo_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::imgr::model::PhotoThumbnail::id_type,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::persist_statement[] =
  "INSERT INTO \"PhotoThumbnail\" "
  "(\"id\", "
  "\"width\", "
  "\"height\", "
  "\"channels\", "
  "\"thumbnail\", "
  "\"photo\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::find_statement[] =
  "SELECT "
  "\"PhotoThumbnail\".\"id\", "
  "\"PhotoThumbnail\".\"width\", "
  "\"PhotoThumbnail\".\"height\", "
  "\"PhotoThumbnail\".\"channels\", "
  "\"PhotoThumbnail\".\"thumbnail\", "
  "\"PhotoThumbnail\".\"photo\" "
  "FROM \"PhotoThumbnail\" "
  "WHERE \"PhotoThumbnail\".\"id\"=?";

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::update_statement[] =
  "UPDATE \"PhotoThumbnail\" "
  "SET "
  "\"width\"=?, "
  "\"height\"=?, "
  "\"channels\"=?, "
  "\"thumbnail\"=?, "
  "\"photo\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::erase_statement[] =
  "DELETE FROM \"PhotoThumbnail\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"PhotoThumbnail\".\"id\",\n"
  "\"PhotoThumbnail\".\"width\",\n"
  "\"PhotoThumbnail\".\"height\",\n"
  "\"PhotoThumbnail\".\"channels\",\n"
  "\"PhotoThumbnail\".\"thumbnail\",\n"
  "\"PhotoThumbnail\".\"photo\"\n"
  "FROM \"PhotoThumbnail\"\n"
  "LEFT JOIN \"Photo\" AS \"photo\" ON \"photo\".\"id\"=\"PhotoThumbnail\".\"photo\"";

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"PhotoThumbnail\"";

  const char access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::table_name[] =
  "\"PhotoThumbnail\"";

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.m_id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.m_id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::pointer_type
  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::object_type >
  access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::imgr::model::PhotoThumbnail, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"PhotoThumbnail\"");
          db.execute ("DROP TABLE IF EXISTS \"Photo\"");
          db.execute ("DROP TABLE IF EXISTS \"Album\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"Album\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"absolute_path\" TEXT NOT NULL,\n"
                      "  \"name\" TEXT NOT NULL,\n"
                      "  \"parent_album\" INTEGER NULL,\n"
                      "  CONSTRAINT \"parent_album_fk\"\n"
                      "    FOREIGN KEY (\"parent_album\")\n"
                      "    REFERENCES \"Album\" (\"id\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE UNIQUE INDEX \"Album_absolute_path_i\"\n"
                      "  ON \"Album\" (\"absolute_path\")");
          db.execute ("CREATE TABLE \"Photo\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"filename\" TEXT NOT NULL,\n"
                      "  \"width\" INTEGER NOT NULL,\n"
                      "  \"height\" INTEGER NOT NULL,\n"
                      "  \"album\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"album_fk\"\n"
                      "    FOREIGN KEY (\"album\")\n"
                      "    REFERENCES \"Album\" (\"id\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE TABLE \"PhotoThumbnail\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"width\" INTEGER NOT NULL,\n"
                      "  \"height\" INTEGER NOT NULL,\n"
                      "  \"channels\" INTEGER NOT NULL,\n"
                      "  \"thumbnail\" BLOB NOT NULL,\n"
                      "  \"photo\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"photo_fk\"\n"
                      "    FOREIGN KEY (\"photo\")\n"
                      "    REFERENCES \"Photo\" (\"id\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE UNIQUE INDEX \"PhotoThumbnail_photo_i\"\n"
                      "  ON \"PhotoThumbnail\" (\"photo\")");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
