@startuml
'https://plantuml.com/sequence-diagram

title Loading thumbnail images with Gallery
participant     wxGallery as gallery
participant     wxApp as app
participant     AlbumManager as manager
database        PhotoStore as store

autonumber

-> gallery : LoadAlbum(album_id)
gallery -> app : get_album_manager()
gallery <-- app: AlbumManagerRef
gallery -> manager : get_album_photos(album_id)
manager -> store : get_album_photos(album_id)
manager <-- store : PhotoList
gallery <-- manager : PhotoList

loop On each Image from the PhotoList
    gallery -> manager : load_photo(photo_id, thumbnail=true)
    manager -> store : load_photo_thumbnail(photo_id)
    manager <-- store : ImageData
    manager -> manager : create_gui_image(ImageData)
    gallery <-- manager : RawImageData
    gallery -> gallery: create_gallery_image(RawImageData)
end

<-- gallery : ok?

@enduml