@startuml
'https://plantuml.com/sequence-diagram

title Loading images with Gallery
participant     wxApp as app
participant     wxGallery as gallery
participant     AlbumManager as manager
database        PhotoStore as store

autonumber

-> gallery : LoadAlbum(album_id)
gallery -> app : get_album_manager()
app --> gallery : AlbumManagerRef
gallery -> manager : get_album_photos(album_id)
manager -> store : get_album_photos(album_id)
store --> manager : PhotoList
manager --> gallery : PhotoList

loop On each Image from the PhotoList
    gallery -> manager : load_photo(photo_id, thumbnail=true)
    manager -> store : load_photo_thumbnail(photo_id)
    store --> manager : ImageData
    manager -> manager : create_gui_image(ImageData)
    manager --> gallery : wxImage
    gallery -> gallery: create_gallery_image(wxImage)
end

@enduml